### ISSUE TITLE
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :    arguments imply differing number of rows: 1, 0

### ISSUE THREAD

**Issue by pablovgd** [krispir/cpc#2]
Hi all

I'm comparing different ways for ms processing, among others xcms and I stumbled on this package. I wanted to give it a try and used following code on a XCMSExp file of processed lc-ms data (polar metabolomics, positive ionisation). XCMS processing was done as follows (using IPO optimized parameters):
```
polar_data <- filterEmptySpectra(raw_data)
param = CentWaveParam(
ppm = 6, #nstrum setup QE orbitrap ms: 10ppm
peakwidth = c(10.406, 36.5) , #instrum setup QE orbitrap ms: 15sec
snthresh = 10,
noise = 15000, #toek todo eval 10+4, 10+5, 10+6 for best balance speed/sensitivity
prefilter = c(3, 100),
mzdiff          = -0.002408,
mzCenterFun     = "wMean",
integrate = 1,
fitgauss = FALSE)
xdata_polar <- findChromPeaks(polar_data,param =param)
mpp <- MergeNeighboringPeaksParam(expandRt = 4)
xdata_polar <- refineChromPeaks(xdata_polar,mpp,BPPARAM = bpparam())
obiwarpparam = ObiwarpParam(binSize = 0.538, distFun = "cor_opt", centerSample = 3, response = 1, gapInit = 0.616, gapExtend = 2.4, factorDiag = 2, factorGap = 1, localAlignment = F, subset =  which(xdata_polar$sample_type == "bio"))
xdata_polar <- adjustRtime(xdata_polar, param = obiwarpparam)
pdp <- PeakDensityParam(sampleGroups = xdata_low$sample_type,
                        minFraction = 0.2, bw = 0.9, minSamples = 1,binSize = 1e-04)
xdata_polar <- groupChromPeaks(xdata_polar,param =pdp)
xdata_polar <- fillChromPeaks(xdata_polar, param=ChromPeakAreaParam())

```
Afterwards for running cpc i use:

```
cpc <- filter_xcms_peaklist(xd = xdata_polar, return_type = "cpc", param = cpc::cpcProcParam(min_sn = 10,min_pts = 10, min_intensity = 10000))

```
First file processes just fine, but during processing of the second file I get this output:
```
Removing existing feature definitions from XCMS object. Run retention alignment and peak filling again after processing.
Processing file: C:\Users\pvgeende\OneDrive - UGent\Laatste polaire raw files\Extra_controle2_pos\bio\220208sss023.mzXML

Found 24348 peak(s).

 Processing peak 24348 of 24348 [================================================================================] in  7m
Finished in 7.4 mins.

Processing file: C:\Users\pvgeende\OneDrive - UGent\Laatste polaire raw files\Extra_controle2_pos\bio\220208sss024.mzXML

Found 24533 peak(s).

 Processing peak 13695 of 24533 [============================================>-----------------------------------] in  4mError in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
In addition: Warning message:
In data.frame(id = as.numeric(sub("CP", "", rownames(x@pt))), x@pt) :
  NAs introduced by coercion
```

Any idea what might be the problem here? Thanks in advance!

Kind regards
Pablo

**Comment by krispir** [comment]
Hi Pablo,

Thank you for reporting the issue!

It looks a bit strange to me that you get that error at that point in the processing, but this is R after all. :) Would it be possible for you to share a reproducible example? For example, woud it be possible for you to share the XCMSnExp object passed to CPC as well as the mzML-file in which the error occured (220208sss024.mzXML)?

Kind regards,
Kristian

**Comment by pablovgd** [comment]
Hi Kristian,

Thanks a lot for the swift response!
You can download both files here: https://we.tl/t-exIlVNS2Q9

Kind regards,
Pablo

**Comment by krispir** [comment]
Hi Pablo,

Thank you for sharing the files. Quick update, unfortunately, the xcms data file was corrupted somehow. I was able to recreate the problem, however, using the script your shared above. I'll see now if I can figure out why the error occurs. I'll keep you updated.

Kind regards,
Kristian

**Comment by krispir** [comment]
Hi Pablo,

Finally, after some digging, I found the root cause of the error. The peak in question had m/z 799.5907 but looking at the raw data there is no actual MS information in the mz range reported by XCMS (another example of strange results coming from XCMS). All I get when I extract it is a vector of 0's which means that no peak is detected by CPC either. In this specific case the list returned from the C++ framework has zero-length values which caused a line-number discrepancy when it was converted to a data.frame.

I have fixed this now in the code and I can now process the file without issues. Please try installing it again from GitHub and let me know if it works for you as well.

Best regards,
Kristian

**Comment by pablovgd** [comment]
Hi Kirstian

Thanks for the update and for the in depth look!
I'll try to reinstall cpc soon and post an update here.

Kind regards
Pablo
